spring:
  application:
    name: ecommerce
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
management:
  endpoints:
    web:
      exposure:
        include: health,info
app:
  security:
    jwt:
      access-ttl: 15m
      refresh-ttl: 14d
